#!/bin/bash
# Use advanced text manipulation tools (jq, awk, sed) to extract specific data from the API response.
jq -r '"\(.name)|\(.type[0].type.name)|\(.weight)|\(.height)"' data.json | awk -F'|' '{printf "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall.\n", name=$1, type=$2, formatted_weight=$3/10, formatted_height=$4/10}'
# The output should be formatted as: "<name> is of type <type>, weighs <weight> and is <height> tall."